# Aritificial intelligence assignment 2024


In dit document wordt een model getraind op de mnist nummers dataset. Het model bevat 3 lagen (Flatten, Dense, Dense/output) 
waar nog mee geexperimenteerd is. Daarnaast wordt de standaard accuracy getoond voor het meten van de nauwkeurigheid van het model.
De loss function sparse_categorical_crossentropy wordt gebruikt en de nauwkeurigheid van het model is het hoogst met epochs = 5 en 
validation_split=0.1. Dit betekend dat de dataset 5x door het model heen gehaald is met forward- en backward propogation.
De validation_split van 0.1 betekend dat 1/100e van de trainingsset als validatie data/held out data dient.

In [11]:
import tensorflow as tf
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, SeparableConv2D, BatchNormalization

mnist = tf.keras.datasets.mnist

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.1


In [12]:
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [13]:
# Normalize the pixel values to be between 0 and 1
# x_train = tf.keras.utils.normalize(x_train, axis=1)
# x_test = tf.keras.utils.normalize(x_test, axis=1)
x_train = (x_train - 0.0) / (255.0 - 0.0)
x_test = (x_test - 0.0) / (255.0 - 0.0)

In [14]:
# Reshape the data if using convolutional neural networks (CNNs)
# x_train = x_train.reshape(-1, 28, 28, 1)
# x_test = x_test.reshape(-1, 28, 28, 1)
x_train = x_train.reshape((x_train.shape + (1,)))
x_test = x_test.reshape((x_test.shape + (1,)))

In [15]:
# Toon de data
print("Training data shape:", x_train.shape)
print("Test data shape:", x_test.shape)

Training data shape: (60000, 28, 28, 1)
Test data shape: (10000, 28, 28, 1)


In [16]:
model = Sequential()

#Maak de 28x28 array plat tot een 1 dimentionale array/ of 
# model.add(Flatten(input_shape=(28, 28)))

#Check wat efficienter is voor de nauwkeurigheid van het model, Conv2D or double Dense layers
model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())

model.add(Dense(128, activation='relu'))

model.add(Dense(10, activation='softmax'))

#Compile the current model
optimizer = SGD(learning_rate=0.01, momentum=0.9)

# model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.compile(optimizer=optimizer,
                          loss='sparse_categorical_crossentropy',
                          metrics=['accuracy'])

C:\Users\thimo\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Na zorgvuldig testen is de conclusie dat er tussen de SDG optimizer en de adam optimizer weinig verschil zit in totale performance.
De sdg optimizer gaat bij de eerste epoch trager, maar bij de tweede epoch sneller dan de adam optimizer wat in totaal uitkomt op hetzelfde.

In [18]:
# Train het model met validatie
history = model.fit(x_train, y_train, epochs=2, batch_size=32)

Epoch 1/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - accuracy: 0.8590 - loss: 0.4343
Epoch 2/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9821 - loss: 0.0552


In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 26, 26, 64)          │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 13, 13, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 11, 11, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 5, 5, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 1600)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         204,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 487,574 (1.86 MB)

 Trainable params: 243,786 (952.29 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 243,788 (952.30 KB)

In [21]:
# Evalueer het model op de testset
test_loss, test_accuracy = model.evaluate(x_test, y_test)

print(f"Test nauwkeurigheid: {test_accuracy:.4f}")


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9847 - loss: 0.0420
Test nauwkeurigheid: 0.9881


In [23]:
# Modelgrootte berekenen
model_size = model.count_params()
model_memory = model_size * 4 / (1024 ** 2)  # 4 bytes per 32-bit float
print(f"Modelgrootte: {model_memory:.2f} MB")

Modelgrootte: 0.93 MB


# In dit deel wordt een nauwkeurigheid van het model getoond door middel van de confusion matrix

In [26]:
from sklearn.metrics import confusion_matrix
import numpy as np

In [27]:
# Maak voorspellingen op de testset
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [28]:
# Bereken de verwarringsmatrix
cm = confusion_matrix(y_test, y_pred_classes)
print("Verwarringsmatrix:")
print(cm)

Verwarringsmatrix:
[[ 973    0    0    0    0    0    1    2    2    2]
 [   0 1129    1    0    1    1    0    2    1    0]
 [   1    3 1018    0    2    0    0    3    5    0]
 [   0    0    2  998    0    3    0    1    5    1]
 [   0    0    0    0  979    0    0    0    0    3]
 [   2    0    0    8    0  877    1    1    1    2]
 [   5    4    0    0    4    4  938    0    3    0]
 [   0    0    7    1    1    0    0 1017    1    1]
 [   3    0    1    1    1    0    0    2  963    3]
 [   0    2    0    0    7    3    0    6    2  989]]


De verwarringsmatrix is te lezen als volgt:
De x as moeten de getallen van 0 tm 9 bevatten die het model voorspelt.
De y as moeten de getallen zijn die gelabeld zijn als 0 tm 9.

In deze matrix kunnen we zien dat klasse 8 op de y-as het meest fout gedaan wordt door het model. Daarnaast kan hieruit geconcludeerd worden dat klasse 7 op de x as het meest fout geraden is door het model